//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agricathon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgricathonModelContainer : DbContext
    {
        public AgricathonModelContainer()
            : base("name=AgricathonModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sector> SectorSet { get; set; }
        public virtual DbSet<Provider> ProviderSet { get; set; }
        public virtual DbSet<Project> ProjectSet { get; set; }
        public virtual DbSet<LegalForm> LegalFormSet { get; set; }
        public virtual DbSet<Activity> ActivitySet { get; set; }
        public virtual DbSet<Location> LocationSet { get; set; }
        public virtual DbSet<Website> WebsiteSet { get; set; }
        public virtual DbSet<Finance> FinanceSet { get; set; }
        public virtual DbSet<Specialist> SpecialistSet { get; set; }
        public virtual DbSet<Contact> ContactSet { get; set; }
    }
}
